## The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
##
## tab delimited samples file ... should have the following 3 columns
## sampleName   path_to_R1_fastq        path_to_R2_fastq
##
samples: "WORKDIR/samples.tsv"
scriptsdir: "WORKDIR/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "WORKDIR/tools.yaml"
cluster: "WORKDIR/cluster.json"
##
### Resources
##
ref_gtf: "/data/CCBR/projects/ccbr1060/Hg38_shRNA_hybrid/Hg38_shRNA.gtf"
star_index_dir: "/data/CCBR/projects/ccbr1060/Hg38_shRNA_hybrid/STAR_index_no_GTF_2.7.6a"
fastqscreen_config: "PIPELINE_HOME/config/fastq_screen_config.txt"
# other paramters
